name: sync_branch
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  sync_branch:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      REPO_BRANCH: peer_review
    steps:
      - uses: actions/checkout@v2
        
      - name: Config git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "noreply@github.com"
          git config --global pull.rebase false
          
      - name: Remote
        run: |
          git remote add ghclass https://github.com/rundel/ghclass.git
      
      - name: Checkout
        run: |
          git checkout -b ${REPO_BRANCH}
      
      - name: Fetch
        run: |
          git fetch ghclass ${REPO_BRANCH}

      - name: Merge
        run: |
          git merge -X theirs ghclass/${REPO_BRANCH} --allow-unrelated-histories -m "Merge"

      - name: Push
        run: |
          git push --force origin ${REPO_BRANCH}
          
